name: env_CoExpPhylo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - networkx
  - plotly
  - pandas
  - csvkit
  - hashlib
  - parallel
  - nohup
  - perl
  - pip:
      - plotly
